```{r fig.height=3, fig.width=4}

library(tidyverse)

set.seed(42)

dat <- 
  tibble(time1 = rnorm(n = 20)) |>
  mutate(time2 = time1 + rnorm(n = 20, sd = 0.5))

corr <- round(cor(dat)[1,2], 2)

mdiff <- dat |>
  summarize(mean_time1 = mean(time1),
            mean_time2 = mean(time2),
            mean_diff = round(mean_time2 - mean_time1, 2)) |>
  pull(mean_diff)

dat |>
  rownames_to_column(var = "id") |>
  pivot_longer(cols = -id,
               names_to = "Timepoint",
               values_to = "Score") |>
  ggplot(aes(Timepoint, Score, group = id)) +
  geom_line() +
  geom_point() +
  theme_linedraw() +
  ggtitle(paste0("Pearson's r = ", corr, ", Cohen's d = ", mdiff)) +
  ylim(-4, 4)

ggsave("example1.png",
       width = 4, 
       height = 3)

```


```{r fig.height=3, fig.width=4}

library(tidyverse)

set.seed(42)

dat <- 
  tibble(time1 = rnorm(n = 20)) |>
  mutate(time2 = rnorm(n = 20))

corr <- round(cor(dat)[1,2], 2)

mdiff <- dat |>
  summarize(mean_time1 = mean(time1),
            mean_time2 = mean(time2),
            mean_diff = round(mean_time2 - mean_time1, 2)) |>
  pull(mean_diff)

dat |>
  rownames_to_column(var = "id") |>
  pivot_longer(cols = -id,
               names_to = "Timepoint",
               values_to = "Score") |>
  ggplot(aes(Timepoint, Score, group = id)) +
  geom_line() +
  geom_point() +
  theme_linedraw() +
  ggtitle(paste0("Pearson's r = ", corr, ", Cohen's d = ", mdiff)) +
  ylim(-4, 4)

ggsave("example2.png",
       width = 4, 
       height = 3)

```


```{r fig.height=3, fig.width=4}

library(tidyverse)

set.seed(42)

dat <- 
  tibble(time1 = rnorm(n = 20)) |>
  mutate(time2 = time1 + 1.4)

corr <- round(cor(dat)[1,2], 2)

mdiff <- dat |>
  summarize(mean_time1 = mean(time1),
            mean_time2 = mean(time2),
            mean_diff = round(mean_time2 - mean_time1, 2)) |>
  pull(mean_diff)

dat |>
  rownames_to_column(var = "id") |>
  pivot_longer(cols = -id,
               names_to = "Timepoint",
               values_to = "Score") |>
  ggplot(aes(Timepoint, Score, group = id)) +
  geom_line() +
  geom_point() +
  theme_linedraw() +
  ggtitle(paste0("Pearson's r = ", corr, ", Cohen's d = ", mdiff)) +
  ylim(-4, 4)

ggsave("example3.png",
       width = 4, 
       height = 3)

```


